name: Vulnerability Scanning Action
description: This action performs security scanning on your code.

inputs:

  log-level:
    description: Log level
    type: choice
    required: false
    options:
      - debug
      - info
      - warn
      - error

  scan-repo:
    description: Wether to scan the local repo path
    type: boolean
    default: true

  target-images:
    description: Space separated list of images to scan.
    type: string
    required: false

  target-gitrepos:
    description: Space separated list of git repositories 
    type: string
    default: true

  vulcan-local-version:
    description: Vulcan local version to use
    type: string
    default: v0.2.1

runs:
  using: composite

  steps:
    - uses: actions/checkout@v3
      if: ${{ inputs.scan-repo }}
      with:
        depth: 1

    - name: Install vulcan-local
      shell: bash
      env:
        VULCAN_LOCAL_VERSION: ${{ inputs.vulcan-local-version }}
      run: |
        curl -sfL https://raw.githubusercontent.com/adevinta/vulcan-local/master/script/get | sh -s -- --version $VULCAN_LOCAL_VERSION

    - name: Scan code
      shell: bash
      env:
        LOG_LEVEL: ${{ inputs.log-level }}
        SCAN_REPO: ${{ inputs.scan-repo }}
        TARGET_IMAGES: ${{ inputs.target-images }}
        TARGET_GITREPOS: ${{ inputs.target-gitrepos }}
      run: $GITHUB_ACTION_PATH/run.sh
