name: Vulnerability Scanning Action
description: This action performs security scanning on your code.

inputs:
  log-level:
    description: 'Log level [error warning info debug]'
    required: false

runs:
  using: composite

  steps:

    - uses: actions/checkout@v3

    - name: Install vulcan-local
      shell: bash
      run: |
        curl -sfL https://raw.githubusercontent.com/adevinta/vulcan-local/master/script/get | sh -s -- --version v0.2.1

    - name: Scan code
      shell: bash
      run: |
        VL_ARGS=()
        if [ -e "${INPUT_LOG_LEVEL}" ]; then
            VL_ARGS+=("-l" "${INPUT_LOG_LEVEL}")
        fi

        vulcan-local -t . "${VL_ARGS[@]}"
