name: Vulnerability Scanning Action
description: This action performs security scanning on your code.
inputs:
  # config-file:
  #   description: 'Config file'
  #   required: false
  #   default: "vulcan.yaml"
  # log-level:
  #   description: 'Log level'
  #   required: false
  #   default: "info"
  # checktypes:
  #   description: 'Checktypes url for Only repository mode'
  #   required: false
  #   default: "https://raw.githubusercontent.com/adevinta/vulcan-local/master/script/checktypes-stable.json"
  # other-options:
  #   description: 'Other options to add'
  #   required: false
  #   default: ""
runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install vulcan-local
      shell: bash
      run: |
        export A=1
        curl -sfL https://raw.githubusercontent.com/adevinta/vulcan-local/master/script/get | sh -s -- --version v0.2.1

    - name: Scan code
      shell: bash
      run: |
        echo $A
        vulcan-local -t .
