name: Vulnerability Scanning Action
description: This action performs security scanning on your code.

inputs:
  log-level:
    description: Log level
    type: choice
    required: false
    options:
      - debug
      - info
      - warn
      - error

runs:
  using: composite

  steps:

    - uses: actions/checkout@v3

    - name: Install vulcan-local
      shell: bash
      run: |
        curl -sfL https://raw.githubusercontent.com/adevinta/vulcan-local/master/script/get | sh -s -- --version v0.2.1

    - name: Scan code
      shell: bash
      env:
        LOG_LEVEL: ${{ inputs.log-level }}
      run: $GITHUB_ACTION_PATH/run.sh
